/*실습 0822 1~14번*/
-- 1번 모든 도서의 이름과 가격을 검색하시오.
SELECT BOOKNAME
     , PRICE
FROM   BOOK;
-- 1-1번 모든 도서의 가격과 이름을 검색하시오.
SELECT PRICE
     , BOOKNAME
FROM   BOOK;
  
-- 2번 모든 도서테이블의 컬럼을 검색하시오
SELECT *
FROM BOOK;

-- 3번 모든 출판사를 검색
SELECT PUBLISHER
FROM   BOOK;

-- 3-*
SELECT DISTINCT PUBLISHER
FROM   BOOK;
  
-- 4번 가격이 20000미만 도서 검색
SELECT *
FROM   BOOK
WHERE  PRICE < 20000;

--5번
SELECT * 
FROM   BOOK
WHERE  PRICE>=10000
AND    PRICE<=20000;

SELECT * 
FROM   BOOK
WHERE PRICE BETWEEN 10000 AND 19999;

-- 6번
SELECT * 
FROM   BOOK
WHERE  PUBLISHER IN('굿스포츠', '대한미디어'); 
-- 6-*
SELECT * 
FROM   BOOK
WHERE  PUBLISHER 
NOT IN('굿스포츠', '대한미디어');

SELECT * 
FROM   BOOK
WHERE  NOT(PUBLISHER='굿스포츠' OR PUBLISHER='대한미디어');

SELECT * 
FROM   BOOK
WHERE  PUBLISHER<>'굿스포츠' AND PUBLISHER<>'대한미디어';

-- 7번
SELECT BOOKNAME
     , PUBLISHER
FROM   BOOK
WHERE  BOOKNAME='축구의 역사';

-- 8번
SELECT BOOKNAME, PUBLISHER
FROM   BOOK
WHERE  BOOKNAME LIKE '축구%';

-- 9번
SELECT *
FROM   BOOK
WHERE  BOOKNAME LIKE '_구%';

--10번
SELECT *
FROM   BOOK
WHERE  PRICE >=20000 
AND    BOOKNAME LIKE '%축구%';


--11번
SELECT *
FROM BOOK
WHERE PUBLISHER IN('굿스포츠','대한미디어');

-- 12번
SELECT * 
FROM BOOK
ORDER BY BOOKNAME;

-- 13번
SELECT   *
FROM     BOOK
ORDER BY PRICE, BOOKNAME;

-- 14번
SELECT   *
FROM     BOOK
ORDER BY PRICE DESC, 
         PUBLISHER;
-- 15번 고객이 주문한 도서의 총판매액
SELECT SUM(SALEPRICE) 
FROM ORDERS;
SELECT SUM(SALEPRICE) 
"총매출" FROM ORDERS;

-- 16번 
SELECT SUM(SALEPRICE)"총매출"
FROM ORDERS
WHERE CUSTID=2;   
-- 17번
SELECT SUM(SALEPRICE) "TOTAL"
     , AVG(SALEPRICE)
     , MIN(SALEPRICE)
     , MAX(SALEPRICE)
FROM   ORDERS;

-- 18번
SELECT COUNT(*) 
FROM   ORDERS;
-- 19번
SELECT   CUSTID
       , COUNT(CUSTID)      "도서수량"
       , SUM(SALEPRICE)     "총액"
FROM     ORDERS
GROUP BY CUSTID;
-- 20번까지만  
-- 가격 8000원이상
-- 고객별 주문의 도서 총수량

SELECT CUSTID
     , COUNT(*) AS "도서수량"
FROM   ORDERS
WHERE  SALEPRICE >= 8000
HAVING COUNT(CUSTID) >= 2
GROUP  BY CUSTID;
