SELECT OWNER,TABLE_NAME,CONSTRAINT_NAME,CONSTRAINT_TYPE, STATUS
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='CUSTOMER';

SELECT TABLE_NAME,COLUMN_NAME,CONSTRAINT_NAME
FROM USER_CONS_COLUMNS
WHERE TABLE_NAME='CUSTOMER';


SELECT UI.TABLE_NAME, 
       UI.INDEX_NAME, 
       UIC.COLUMN_NAME
FROM   USER_INDEXES UI
JOIN   USER_IND_COLUMNS UIC
ON     UI.INDEX_NAME = UIC.INDEX_NAME
WHERE  UI.TABLE_NAME = 'ORDERS';

SELECT TABLE_NAME, INDEX_NAME
FROM USER_INDEXES
WHERE TABLE_NAME='ORDERS';

SELECT INDEX_NAME, TABLE_NAME, COLUMN_NAME
FROM   USER_IND_COLUMNS
WHERE  TABLE_NAME='ORDERS';



SELECT * FROM ORDERS;
SELECT * FROM CUSTOMER;


SELECT     COUNT(O.BOOKID) "도서총수", 
           SUM(O.SALEPRICE) "총구매액"
FROM       ORDERS O, 
           CUSTOMER C
WHERE      O.CUSTID = C.CUSTID
           AND C.NAME = '장미란'
           AND O.ORDERDATE BETWEEN TO_DATE('20140705', 'YYYYMMDD') 
           AND TO_DATE('20140710235959', 'YYYYMMDDHH24MISS');


SELECT * FROM ORDERS;

SELECT C.NAME
FROM   CUSTOMER C
WHERE  C.CUSTID 
NOT IN (SELECT O.CUSTID
        FROM ORDERS O);

DELETE FROM BOOK WHERE BOOKID=11;

DESC BOOK;

SELECT * FROM BOOK;

INSERT INTO BOOK (
      BOOKID
    , BOOKNAME
    , PUBLISHER
    , PRICE
) VALUES (
    11
  , '탁구 교본'
  , '굿스포츠'
  , 20000
);
ROLLBACK;
COMMIT;
SELECT * FROM CUSTOMER;

INSERT INTO CUSTOMER (
      CUSTID
    , NAME
    , ADDRESS
    , PHONE
) VALUES (
    6
  , '신유빈'
  , '대한민국 경기도'
  , '010-1234-4321'
);

COMMIT;
ROLLBACK;
SELECT * FROM BOOK;

INSERT INTO BOOK VALUES(9,'올림픽 이야기','삼성당',7500);

DELETE FROM BOOK 
WHERE BOOKNAME = '골프 바이블';

COMMIT;

DELETE FROM BOOK 
WHERE PUBLISHER = '삼성당';

COMMIT;


ROLLBACK;
SELECT * FROM BOOK;



UPDATE BOOK
SET    PUBLISHER = '이상스포츠'
WHERE  PUBLISHER = '이상미디어';

COMMIT;

SELECT * FROM CUSTOMER;


UPDATE CUSTOMER
SET    PHONE = '010-3333-0909'
WHERE  NAME =  '박세리';

COMMIT;

SELECT * FROM DICTIONARY;
