CREATE TABLE DEPARTMENT(
     DEPTNO    NUMBER(3) PRIMARY KEY
    ,DEPTNAME  CHAR(10)  NOT NULL
    ,FLOOR     NUMBER(2)
);

CREATE TABLE EMPLOYEE(
     EMPNO    VARCHAR2(4)  PRIMARY KEY
    ,EMPNAME  VARCHAR2(20) NOT NULL
    ,TITLE    VARCHAR2(10)
    ,SALARY   NUMBER(8)
    ,DEPTNO   NUMBER(2)    NOT NULL 
              CONSTRAINT   EMP_DEPTNO_FK
              REFERENCES   DEPARTMENT(DEPTNO)
);

DESC DEPARTMENT;
DESC EMPLOYEE;

SELECT OWNER, TABLE_NAME,CONSTRAINT_NAME,CONSTRAINT_TYPE, STATUS
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='EMPLOYEE';

SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME
FROM   USER_CONS_COLUMNS
WHERE TABLE_NAME = 'EMPLOYEE';

DELETE FROM EMPLOYEE WHERE EMPNO = '1003';

-- Employee

INSERT INTO EMPLOYEE (EMPNO, EMPNAME, TITLE, SALARY, DEPTNO)
VALUES ('1003', '조민희', '과장', 3000000, 2);

INSERT INTO EMPLOYEE (EMPNO, EMPNAME, TITLE, SALARY, DEPTNO)
VALUES ('1365', '김상원', '사원', 1500000, 1);

INSERT INTO EMPLOYEE (EMPNO, EMPNAME, TITLE, SALARY, DEPTNO)
VALUES ('2106', '김창섭', '대리', 2500000, 2);

INSERT INTO EMPLOYEE (EMPNO, EMPNAME, TITLE, SALARY, DEPTNO)
VALUES ('3011', '이수민', '부장', 4000000, 3);

INSERT INTO EMPLOYEE (EMPNO, EMPNAME, TITLE, SALARY, DEPTNO)
VALUES ('3426', '박영권', '과장', 3000000, 3);

INSERT INTO EMPLOYEE (EMPNO, EMPNAME, TITLE, SALARY, DEPTNO)
VALUES ('3427', '최종철', '사원', 1500000, 1);

INSERT INTO EMPLOYEE (EMPNO, EMPNAME, TITLE, SALARY, DEPTNO)
VALUES ('4377', '이성래', '사장', 5000000, 2);

COMMIT;

-- Department
INSERT INTO DEPARTMENT (DEPTNO, DEPTNAME, FLOOR)
VALUES (1, '영업', 8);

INSERT INTO DEPARTMENT (DEPTNO, DEPTNAME, FLOOR)
VALUES (2, '기획', 10);

INSERT INTO DEPARTMENT (DEPTNO, DEPTNAME, FLOOR)
VALUES (3, '개발', 9);

INSERT INTO DEPARTMENT (DEPTNO, DEPTNAME, FLOOR)
VALUES (4, '총무', 7);

COMMIT;



DELETE FROM EMPLOYEE   WHERE DEPTNO=4;
DELETE FROM DEPARTMENT WHERE DEPTNO=4;

COMMIT;





SELECT * FROM EMPLOYEE;

DESC EMPLOYEE;

UPDATE EMPLOYEE
SET DEPTNO = 3,               
    SALARY = SALARY * 1.05    
WHERE EMPNO = '2106';         

COMMIT;


SELECT * FROM DEPARTMENT;
SELECT * FROM EMPLOYEE;


SELECT EMPNAME
FROM   EMPLOYEE 
WHERE DEPTNO IN 
            ( SELECT DEPTNO
              FROM DEPARTMENT
              WHERE DEPTNAME 
              IN ('영업', '개발'));



SELECT EMPNAME
     , TITLE
     , SALARY
FROM   EMPLOYEE
     , DEPARTMENT
WHERE  EMPLOYEE.DEPTNO = DEPARTMENT.DEPTNO 
AND    DEPARTMENT.DEPTNAME = '기획';

SELECT EMPNAME
     , TITLE
     , SALARY
FROM   EMPLOYEE
JOIN   DEPARTMENT
ON     EMPLOYEE.DEPTNO = DEPARTMENT.DEPTNO
WHERE  DEPARTMENT.DEPTNAME = '기획';






SELECT * FROM EMPLOYEE WHERE EMPNAME='이성래';


CREATE INDEX IDX_EMP_NAME ON EMPLOYEE(EMPNAME);


SELECT * FROM EMPLOYEE WHERE EMPNAME='이성래';




SELECT CR.TABLE_NAME
,CC.COLUMN_NAME
,CR.CONSTRAINT_NAME
,CR.CONSTRAINT_TYPE
,CR.SEARCH_CONDITION
, CR.STATUS
FROM USER_CONSTRAINTS CR
,USER_CONS_COLUMNS CC
WHERE CR.TABLE_NAME = CC.TABLE_NAME
AND CR.CONSTRAINT_NAME = CC.CONSTRAINT_NAME
AND CR.TABLE_NAME = 'EMPLOYEE';

