SELECT * FROM BOOK;
SELECT * FROM ORDERS;
SELECT * FROM CUSTOMER;
-- 1-1
SELECT BOOKNAME FROM BOOK WHERE BOOKID=1;

--1-2
SELECT BOOKNAME FROM BOOK WHERE PRICE >= 20000;

--1-3
-- 이름은 in을 쓰는 것이 좋다.

SELECT SUM(O.SALEPRICE) "총 구매액"
  FROM ORDERS O
 WHERE O.CUSTID IN (
    SELECT C.CUSTID
      FROM CUSTOMER C
     WHERE NAME = '박지성'
);  

SELECT SUM(O.SALEPRICE) "총 구매액"
FROM ORDERS O JOIN CUSTOMER C
ON O.CUSTID=C.CUSTID WHERE NAME='박지성';

--1-4

SELECT COUNT(*) "도서 수"
  FROM ORDERS O
 WHERE O.CUSTID IN (
    SELECT C.CUSTID
      FROM CUSTOMER C
     WHERE NAME = '박지성'
);  

--1-5
SELECT COUNT(DISTINCT(PUBLISHER)) "도서 수"
  FROM BOOK B
  JOIN ORDERS O
  ON B.BOOKID=O.BOOKID
 WHERE O.CUSTID IN (
    SELECT C.CUSTID
      FROM CUSTOMER C
     WHERE NAME = '박지성'
);  

--1-6
SELECT B.BOOKNAME
     , B.PRICE
     , B.PRICE - O.SALEPRICE "차이"
FROM  BOOK B
JOIN  ORDERS O ON B.BOOKID = O.BOOKID
WHERE O.CUSTID IN (
    SELECT C.CUSTID
      FROM CUSTOMER C
     WHERE NAME = '박지성'
);

-- 1-7 -- 박지성이 구매하지 않은 도서의 이름

-- MINUS
SELECT BOOKNAME 
  FROM BOOK
MINUS
SELECT B.BOOKNAME
  FROM BOOK B
  JOIN ORDERS O
    ON B.BOOKID = O.BOOKID
 WHERE O.CUSTID IN (
    SELECT C.CUSTID
      FROM CUSTOMER C
     WHERE NAME = '박지성'
);

-- 강사답안
SELECT BOOKNAME
FROM  BOOK B1
MINUS
SELECT BOOKNAME
FROM CUSOTMER
,ORDERS
,BOOK
WHERE CUSTOMER.CUSTID =ORDERS.CUSTID
AND 


-- NOT EXISTS
SELECT B.BOOKNAME
  FROM BOOK B
 WHERE NOT EXISTS (
    SELECT 1
      FROM ORDERS O
     WHERE O.BOOKID = B.BOOKID
       AND EXISTS (
         SELECT 1
           FROM CUSTOMER C
          WHERE C.CUSTID = O.CUSTID
            AND C.NAME = '박지성'
       )
);
-- 강사답안
SELECT BOOKNAME
  FROM BOOK B1
 WHERE NOT EXISTS (
    SELECT BOOKNAME
      FROM  CUSTOMER
           ,ORDERS
       WHERE CUSTOMER.CUSTID=ORDERS.CUSTID
       AND  ORDERS.BOOKID=B1.BOOKID
       AND CUSTOMER.NAME='박지성'
);






SELECT DISTINCT(B.BOOKNAME)
  FROM BOOK B
FULL OUTER JOIN ORDERS O
    ON B.BOOKID = O.BOOKID
 WHERE O.CUSTID NOT IN (
    SELECT C.CUSTID
      FROM CUSTOMER C
     WHERE C.NAME = '박지성'
);

SELECT B.BOOKNAME
FROM   BOOK B
JOIN   ORDERS O 
ON     B.BOOKID = O.BOOKID
WHERE O.CUSTID NOT IN (SELECT C.CUSTID
FROM CUSTOMER C
WHERE C.NAME = '박지성'
);

SELECT B.BOOKNAME
FROM   BOOK B
JOIN   ORDERS O
ON     B.BOOKID = O.BOOKID
FULL OUTER JOIN CUSTOMER C
ON        O.CUSTID = C.CUSTID
AND C.NAME='박지성'
WHERE   C.CUSTID IS NULL;


--2-1
SELECT * FROM BOOK;
SELECT * FROM ORDERS;
SELECT * FROM CUSTOMER;

SELECT COUNT(*) FROM BOOK;
--2-2
SELECT COUNT(DISTINCT(PUBLISHER)) FROM BOOK;
--2-3
SELECT DISTINCT(C.NAME)
     , C.ADDRESS
  FROM CUSTOMER C
  JOIN ORDERS O ON C.CUSTID = O.CUSTID;
  
  
--2-4
SELECT ORDERID FROM ORDERS
WHERE ORDERDATE >= TO_DATE(20140704,'YYYYMMDD')
AND    ORDERDATE < TO_DATE(20140708,'YYYYMMDD');
-- 마지막날 시간초 주의

-- 강사답
SELECT ORDERID FROM ORDERS
WHERE ORDERDATE BETWEEN TO_DATE(20140704,'YYYYMMDD')
AND   TO_DATE(20140707235959,'YYYYMMDDHH24MISS');

--2-5
SELECT ORDERID FROM ORDERS
MINUS
SELECT ORDERID FROM ORDERS
WHERE ORDERDATE >= TO_DATE(20140704,'YYYYMMDD')
AND    ORDERDATE < TO_DATE(20140708,'YYYYMMDD');

-- 강사답
SELECT ORDERID FROM ORDERS
WHERE ORDERDATE NOT BETWEEN TO_DATE(20140704,'YYYYMMDD')
AND   TO_DATE(20140707235959,'YYYYMMDDHH24MISS');

-- NOT 에
-- 우선순위 NOT -> AND -> OR
SELECT ORDERID FROM ORDERS
WHERE NOT(ORDERDATE >= TO_DATE(20140704,'YYYYMMDD')
AND    ORDERDATE < TO_DATE(20140708,'YYYYMMDD'));

--2-6
SELECT * FROM CUSTOMER;

SELECT NAME
     , ADDRESS
  FROM CUSTOMER
 WHERE NAME LIKE '김%';

--2-7
SELECT NAME
     , ADDRESS
  FROM CUSTOMER
 WHERE NAME LIKE '김_아';
--2-8 
SELECT NAME
  FROM CUSTOMER
 WHERE CUSTID NOT IN (
    SELECT CUSTID
      FROM ORDERS
);

--2-9
SELECT * FROM ORDERS;
-- NVL NN이 안되어있을때
SELECT SUM(SALEPRICE)
     , AVG(NVL(SALEPRICE, 0))
  FROM ORDERS;

DESC ORDERS;

--2-10
SELECT C.NAME
     , SUM(O.SALEPRICE)
  FROM CUSTOMER C
  JOIN ORDERS O ON C.CUSTID = O.CUSTID
 GROUP BY C.NAME;
 
 --2-11
 SELECT C.NAME, B.BOOKNAME 
 FROM CUSTOMER C JOIN ORDERS O
 ON C.CUSTID=O.CUSTID
JOIN BOOK B ON O.BOOKID = B.BOOKID;

--2-12 DIFFICULT

SELECT MAX(B.PRICE-O.SALEPRICE) "차이"
FROM   BOOK B JOIN ORDERS O
ON B.BOOKID=O.BOOKID;


SELECT * FROM ORDERS;

SELECT O.ORDERID FROM BOOK B
JOIN ORDERS O
ON B.BOOKID=O.BOOKID
WHERE B.PRICE-O.SALEPRICE = 
(SELECT MAX(B1.PRICE-O1.SALEPRICE)
FROM BOOK B1 
JOIN ORDERS O1
ON B1.BOOKID=O1.BOOKID
WHERE O1.ORDERID = O.ORDERID);  

SELECT O.ORDERID
     , B.PRICE - O.SALEPRICE AS "차이"
     , ROW_NUMBER() OVER (ORDER BY B.PRICE -O.SALEPRICE DESC) AS RN
  FROM BOOK B
  JOIN ORDERS O ON B.BOOKID = O.BOOKID
 WHERE B.PRICE - O.SALEPRICE = (
    SELECT MAX(B2.PRICE - O2.SALEPRICE)
      FROM BOOK B2
      JOIN ORDERS O2 ON B2.BOOKID = O2.BOOKID
     WHERE O2.ORDERID = O.ORDERID
);

SELECT ORDERID, "차이"
FROM (SELECT O.ORDERID
     , B.PRICE - O.SALEPRICE AS "차이"
     , ROW_NUMBER() OVER (ORDER BY B.PRICE -O.SALEPRICE DESC) AS RN
  FROM BOOK B
  JOIN ORDERS O ON B.BOOKID = O.BOOKID
 WHERE B.PRICE - O.SALEPRICE = (
    SELECT MAX(B2.PRICE - O2.SALEPRICE)
      FROM BOOK B2
      JOIN ORDERS O2 ON B2.BOOKID = O2.BOOKID
     WHERE O2.ORDERID = O.ORDERID
))
WHERE RN=1;


-- 강사답
SELECT *
FROM   BOOK
,ORDERS
WHERE BOOK.BOOKID =ORDERS.BOOKID
AND PRICE -SALEPRICE=
(SELECT MAX(PRICE-SALEPRICE) FROM BOOK, ORDERS WHERE BOOK.BOOKID=ORDERS.BOOKID);

SELECT ORDERID, "차이"
FROM (
    SELECT 
        O.ORDERID, 
        B.PRICE - O.SALEPRICE AS "차이",
        ROW_NUMBER() OVER (ORDER BY B.PRICE - O.SALEPRICE DESC) AS rn
    FROM 
        BOOK B 
    JOIN 
        ORDERS O ON B.BOOKID = O.BOOKID
) 
WHERE rn = 1;



--2-13
SELECT C.NAME
  FROM CUSTOMER C
  JOIN ORDERS O ON C.CUSTID = O.CUSTID
 GROUP BY C.NAME HAVING AVG(NVL(O.SALEPRICE,0)) >
(SELECT
AVG(NVL(O1.SALEPRICE,0)) FROM ORDERS O1);

--3-1
SELECT C.NAME
  FROM CUSTOMER C
JOIN ORDERS O
ON C.CUSTID=O.CUSTID
JOIN BOOK B
ON B.BOOKID=O.BOOKID
WHERE B.PUBLISHER IN(
SELECT PUBLISHER
  FROM BOOK B
  JOIN ORDERS O ON B.BOOKID = O.BOOKID
  JOIN CUSTOMER C ON O.CUSTID=C.CUSTID
  WHERE C.NAME='박지성')
MINUS 
SELECT PUBLISHER
  FROM BOOK B
  JOIN ORDERS O ON B.BOOKID = O.BOOKID
  JOIN CUSTOMER C ON O.CUSTID=C.CUSTID
  WHERE C.NAME='박지성';
  
  -- 강사답
  -- IN 서브쿼리 박지성 , 박지성말고 다른 고객, 
  
SELECT CUSTOMER.NAME AS CUSTOMER_NAME, ORDERS.ORDERID, BOOK.BOOKNAME
  FROM CUSTOMER, ORDERS, BOOK
 WHERE CUSTOMER.CUSTID = ORDERS.CUSTID
   AND ORDERS.BOOKID = BOOK.BOOKID
   AND CUSTOMER.NAME <> '박지성'
   AND BOOK.PUBLISHER IN (
       SELECT BOOK.PUBLISHER
         FROM CUSTOMER, ORDERS, BOOK
        WHERE CUSTOMER.CUSTID = ORDERS.CUSTID
          AND ORDERS.BOOKID = BOOK.BOOKID
          AND CUSTOMER.NAME = '박지성'
   );
   
SELECT NAME
  FROM CUSTOMER C1
 WHERE 2 <= (
    SELECT COUNT(DISTINCT B.PUBLISHER)
      FROM CUSTOMER C2, ORDERS O, BOOK B
     WHERE C2.CUSTID = O.CUSTID
       AND O.BOOKID = B.BOOKID
       AND C2.NAME = C1.NAME
);

SELECT NAME
FROM   CUSTOMER C1
WHERE EXISTS (SELECT * FROM CUSTOMER C2, ORDERS O, BOOK B
WHERE C2.CUSTID=O.CUSTID AND O.BOOKID =B.BOOKID AND C2.NAME=C1.NAME
GROUP BY B.PUBLISHER HAVING COUNT(DISTINCT B.PUBLISHER) >=2);

SELECT C1.NAME
  FROM CUSTOMER C1
 WHERE  C1.NAME <> '박지성'
   AND EXISTS (
    SELECT 1
      FROM CUSTOMER C2
      JOIN ORDERS O
        ON C2.CUSTID = O.CUSTID
      JOIN BOOK B
        ON O.BOOKID = B.BOOKID
     WHERE C2.NAME = C1.NAME
     GROUP BY C2.NAME
    HAVING COUNT(DISTINCT B.PUBLISHER) >= 2
);

SELECT NAME
FROM   CUSTOMER
,ORDERS
,BOOK
WHERE CUSTOMER.CUSTID=ORDERS.CUSTID
AND ORDERS.BOOKID=BOOK.BOOKID
GROUP BY NAME
HAVING COUNT(DISTINCT PUBLISHER)>=2;

   

--3-2
SELECT DISTINCT(C.NAME) FROM CUSTOMER C JOIN ORDERS O
ON C.CUSTID=O.CUSTID
JOIN BOOK B
ON B.BOOKID=O.BOOKID
WHERE C.CUSTID IN (SELECT O2.CUSTID
  FROM ORDERS O2
 GROUP BY O2.CUSTID
HAVING COUNT(O2.BOOKID) > 1);

--3-3
SELECT * FROM ORDERS;
SELECT COUNT(CUSTID)*0.3 FROM CUSTOMER;

SELECT * FROM CUSTOMERS;

SELECT BOOKID, COUNT(CUSTID) FROM ORDERS GROUP BY BOOKID
HAVING COUNT(CUSTID)> (SELECT COUNT(CUSTID)*0.3 FROM CUSTOMER);

SELECT DISTINCT ( B.BOOKNAME )
FROM BOOK B
JOIN ORDERS O ON B.BOOKID = O.BOOKID
WHERE B.BOOKID IN (
      SELECT O1.BOOKID
      FROM ORDERS O1
      GROUP BY O1.BOOKID
      HAVING COUNT(O1.CUSTID) > 
        (SELECT COUNT(CUSTID) * 0.3
        FROM CUSTOMER C)
);




--4-1
SELECT * FROM BOOK;
DESC BOOK;

INSERT INTO BOOK(BOOKID,BOOKNAME,PUBLISHER,PRICE) VALUES
('23','스포츠 세계','대한미디어',10000);
COMMIT;
--4-2
DELETE FROM BOOK WHERE PUBLISHER='삼성당';
COMMIT;

DESC ORDERS;
--4-3
DELETE FROM BOOK WHERE PUBLISHER='이상미디어';
-- ORDERS에서 BOOKID로 외래키를 지정해놓았기 때문

--4-4
SELECT * FROM BOOK;

UPDATE BOOK SET PUBLISHER='대한출판사' WHERE PUBLISHER='대한미디어';

COMMIT;

--4-5

CREATE TABLE BOOKCOMPANY(
NAME VARCHAR2(20) PRIMARY KEY
,ADDRESS VARCHAR2(20)
,BEGIN   DATE);

--4-6
ALTER TABLE BOOKCOMPANY 
ADD (WEBADDRESS VARCHAR2(30));

--4-7-
INSERT INTO BOOKCOMPANY(NAME, ADDRESS, BEGIN, WEBADDRESS)
VALUES ('한빛아카데미','서울시 마포구',TO_DATE(19930101,'YYYYMMDD'),'http://hanbit.co.kr');


