SELECT * FROM EMPLOYEES;
SELECT * FROM JOBS;
SELECT * FROM TAB;
--A. 문제0

SELECT EMPLOYEE_ID "사원번호"
     , FIRST_NAME || ' ' || LAST_NAME "NAME"
     , SALARY "급여"
     , JOB_ID "업무"
     , HIRE_DATE "입사일"
     , MANAGER_ID "상사의 사원번호"
  FROM EMPLOYEES;


--A. 문제1

SELECT 
     FIRST_NAME || ' ' || LAST_NAME "NAME"
     , JOBS.JOB_TITLE "업무" 
     , SALARY                 "급여"
     , SALARY * 12 + 100      "INCREASE ANN_SALARY"
     , (SALARY + 100) * 12    "INCREASE SALARY"
  FROM EMPLOYEES,JOBS
  WHERE  EMPLOYEES.JOB_ID = JOBS.JOB_ID;

--A. 문제2 
SELECT '성:' || LAST_NAME || '1YEAR SALARY = $' || SALARY * 12 "1YEAR SALARY"
  FROM EMPLOYEES;
  
 -- A. 문제3
 SELECT * FROM TAB;
 SELECT * FROM EMPLOYEES;
 SELECT * FROM DEPARTMENTS;
 SELECT * FROM JOBS;
 SELECT * FROM JOB_HISTORY;
 
 DESC JOBS;
 
SELECT DEPARTMENTS.DEPARTMENT_NAME
       ,JOBS.JOB_TITLE
FROM DEPARTMENTS
,JOBS
,EMPLOYEES
WHERE DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
AND JOBS.JOB_ID=EMPLOYEES.JOB_ID
GROUP BY DEPARTMENTS.DEPARTMENT_NAME,JOBS.JOB_TITLE
ORDER BY 1, 2;


-- a.2.
--문제0
SELECT FIRST_NAME || ' ' || LAST_NAME "이름"
        ,SALARY
FROM EMPLOYEES WHERE SALARY BETWEEN 7000 AND 10000 ORDER BY 2;

-- 문제1


SELECT LAST_NAME
FROM   EMPLOYEES
WHERE  LAST_NAME LIKE '%e%' and LAST_NAME LIKE '%o%';
 
-- 문제2 
SELECT FIRST_NAME || ' ' || LAST_NAME "이름"
     , JOBS.JOB_TITLE "업무"
     , HIRE_DATE "입사일"
  FROM EMPLOYEES
       ,JOBS
 WHERE EMPLOYEES.JOB_ID=JOBS.JOB_ID
 AND HIRE_DATE BETWEEN TO_DATE(20060520, 'YYYYMMDD') 
 AND TO_DATE(20070520235959, 'YYYYMMDDHH24MISS')
 ORDER BY 3;
 
--문제3
SELECT FIRST_NAME || ' ' || LAST_NAME "NAME"
     , SALARY
     , JOBS.JOB_TITLE "업무"
     , COMMISSION_PCT "수당율"
  FROM EMPLOYEES 
       ,JOBS
  WHERE EMPLOYEES.JOB_ID=JOBS.JOB_ID 
  AND COMMISSION_PCT IS NOT NULL
  ORDER BY 2, 4;
  
  
-- A.3
--문제 0
SELECT EMPLOYEE_ID
,FIRST_NAME || ' ' || LAST_NAME "NAME"
,SALARY, ROUND(SALARY * 1.123,0) FROM EMPLOYEES
WHERE DEPARTMENT_ID=60;

--문제1

SELECT    FIRST_NAME || ' ' || LAST_NAME || ' IS A ' || JOBS.JOB_TITLE "EMPLOYEE JOBS"
  FROM    EMPLOYEES
        , JOBS
  WHERE EMPLOYEES.JOB_ID=JOBS.JOB_ID 
  AND LAST_NAME LIKE '%s';

--문제2
SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM JOBS;
SELECT * FROM JOB_HISTORY;
 
SELECT  FIRST_NAME || ' ' || LAST_NAME "NAME"
    ,   SALARY
    ,   CASE WHEN COMMISSION_PCT IS NULL THEN 'SALARY ONLY'
        ELSE 'SALARY+COMMISSION'
        END AS SALARY_TYPE
FROM EMPLOYEES;


SELECT  FIRST_NAME || ' ' || LAST_NAME "NAME"
    ,   HIRE_DATE
    ,   TO_CHAR(HIRE_DATE,'DAY')
FROM EMPLOYEES
ORDER BY 
DECODE(TO_CHAR(HIRE_DATE,'D'),2,1,2,2,3,3,4,4,5,5,6,6,7,7);


